spring.application.name=reservas


spring.datasource.url=jdbc:postgresql://localhost:5434/dbreservas
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
server.port=8082
